# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def load_fixture_data(apps, schema_editor):
        from django.core.management import call_command
        call_command("loaddata", "permitType")

    operations = [
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RunPython(load_fixture_data),
    ]
